id: I360D3C78
legacy_id: P000811
ocr_import_info:
  bdrc_scan_id: W3PD1002
  source: bdrc
  ocr_info:
    timestamp: '2021-04-05T09:33:02'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T17:09:20.261704+00:00'
last_modified: 2022-09-04 01:19:45.347171
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3PD1002
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW3PD1002
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། མཁྱེན་བརྩེའི་དབང་པོ།
  author: མཁྱེན་བརྩེའི་དབང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.9738680412971619
  ocr_word_median_confidence_index: 0.99
quality: null
bases:
  I1KG81115:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG81115
      total_pages: 720
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG81115.txt
    statistics:
      ocr_word_median_confidence_index: 0.99
      ocr_word_mean_confidence_index: 0.9790583183896143
    legacy_id: v003
  I1KG81129:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG81129
      total_pages: 590
      volume_number: 17
      volume_pages_bdrc_intro: 2
    order: 17
    base_file: I1KG81129.txt
    statistics:
      ocr_word_median_confidence_index: 0.99
      ocr_word_mean_confidence_index: 0.9700001280909958
    legacy_id: v017
  I1KG81121:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG81121
      total_pages: 480
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I1KG81121.txt
    statistics:
      ocr_word_median_confidence_index: 0.99
      ocr_word_mean_confidence_index: 0.9773630218268444
    legacy_id: v009
  I1KG81127:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG81127
      total_pages: 642
      volume_number: 15
      volume_pages_bdrc_intro: 2
    order: 15
    base_file: I1KG81127.txt
    statistics:
      ocr_word_median_confidence_index: 0.99
      ocr_word_mean_confidence_index: 0.9671661791202242
    legacy_id: v015
  I1KG81126:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG81126
      total_pages: 628
      volume_number: 14
      volume_pages_bdrc_intro: 2
    order: 14
    base_file: I1KG81126.txt
    statistics:
      ocr_word_median_confidence_index: 0.99
      ocr_word_mean_confidence_index: 0.9647568756296213
    legacy_id: v014
  I1KG81124:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG81124
      total_pages: 588
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I1KG81124.txt
    statistics:
      ocr_word_median_confidence_index: 0.99
      ocr_word_mean_confidence_index: 0.9679169058141537
    legacy_id: v012
  I1KG81128:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG81128
      total_pages: 596
      volume_number: 16
      volume_pages_bdrc_intro: 2
    order: 16
    base_file: I1KG81128.txt
    statistics:
      ocr_word_median_confidence_index: 0.99
      ocr_word_mean_confidence_index: 0.9599231973066452
    legacy_id: v016
  I1KG81136:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG81136
      total_pages: 504
      volume_number: 24
      volume_pages_bdrc_intro: 2
    order: 24
    base_file: I1KG81136.txt
    statistics:
      ocr_word_median_confidence_index: 0.99
      ocr_word_mean_confidence_index: 0.976203423040209
    legacy_id: v024
  I1KG81135:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG81135
      total_pages: 494
      volume_number: 23
      volume_pages_bdrc_intro: 2
    order: 23
    base_file: I1KG81135.txt
    statistics:
      ocr_word_median_confidence_index: 0.99
      ocr_word_mean_confidence_index: 0.9793282972810265
    legacy_id: v023
  I1KG81114:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG81114
      total_pages: 488
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG81114.txt
    statistics:
      ocr_word_median_confidence_index: 0.99
      ocr_word_mean_confidence_index: 0.9792247057470382
    legacy_id: v002
  I1KG81137:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG81137
      total_pages: 320
      volume_number: 25
      volume_pages_bdrc_intro: 2
    order: 25
    base_file: I1KG81137.txt
    statistics:
      ocr_word_median_confidence_index: 0.99
      ocr_word_mean_confidence_index: 0.9819455988383737
    legacy_id: v025
  I1KG81122:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG81122
      total_pages: 564
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I1KG81122.txt
    statistics:
      ocr_word_median_confidence_index: 0.99
      ocr_word_mean_confidence_index: 0.9752610447588126
    legacy_id: v010
  I1KG81118:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG81118
      total_pages: 564
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I1KG81118.txt
    statistics:
      ocr_word_median_confidence_index: 0.99
      ocr_word_mean_confidence_index: 0.9798557887843381
    legacy_id: v006
  I1KG81117:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG81117
      total_pages: 640
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1KG81117.txt
    statistics:
      ocr_word_median_confidence_index: 0.99
      ocr_word_mean_confidence_index: 0.9816368020070892
    legacy_id: v005
  I1KG81132:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG81132
      total_pages: 594
      volume_number: 20
      volume_pages_bdrc_intro: 2
    order: 20
    base_file: I1KG81132.txt
    statistics:
      ocr_word_median_confidence_index: 0.99
      ocr_word_mean_confidence_index: 0.9664481251583481
    legacy_id: v020
  I1KG81119:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG81119
      total_pages: 548
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I1KG81119.txt
    statistics:
      ocr_word_median_confidence_index: 0.99
      ocr_word_mean_confidence_index: 0.9736462714540812
    legacy_id: v007
  I1KG81131:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG81131
      total_pages: 574
      volume_number: 19
      volume_pages_bdrc_intro: 2
    order: 19
    base_file: I1KG81131.txt
    statistics:
      ocr_word_median_confidence_index: 0.99
      ocr_word_mean_confidence_index: 0.9799356059536249
    legacy_id: v019
  I1KG81130:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG81130
      total_pages: 538
      volume_number: 18
      volume_pages_bdrc_intro: 2
    order: 18
    base_file: I1KG81130.txt
    statistics:
      ocr_word_median_confidence_index: 0.99
      ocr_word_mean_confidence_index: 0.9799615353910689
    legacy_id: v018
  I1KG81113:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG81113
      total_pages: 525
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG81113.txt
    statistics:
      ocr_word_median_confidence_index: 0.99
      ocr_word_mean_confidence_index: 0.9682440124363662
    legacy_id: v001
  I1KG81120:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG81120
      total_pages: 538
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I1KG81120.txt
    statistics:
      ocr_word_median_confidence_index: 0.99
      ocr_word_mean_confidence_index: 0.9752495254607141
    legacy_id: v008
  I1KG81125:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG81125
      total_pages: 646
      volume_number: 13
      volume_pages_bdrc_intro: 2
    order: 13
    base_file: I1KG81125.txt
    statistics:
      ocr_word_median_confidence_index: 0.99
      ocr_word_mean_confidence_index: 0.9662513270309894
    legacy_id: v013
  I1KG81123:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG81123
      total_pages: 590
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I1KG81123.txt
    statistics:
      ocr_word_median_confidence_index: 0.99
      ocr_word_mean_confidence_index: 0.9767058111990323
    legacy_id: v011
  I1KG81134:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG81134
      total_pages: 660
      volume_number: 22
      volume_pages_bdrc_intro: 2
    order: 22
    base_file: I1KG81134.txt
    statistics:
      ocr_word_median_confidence_index: 0.99
      ocr_word_mean_confidence_index: 0.9781850568796303
    legacy_id: v022
  I1KG81116:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG81116
      total_pages: 730
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG81116.txt
    statistics:
      ocr_word_median_confidence_index: 0.99
      ocr_word_mean_confidence_index: 0.9799688271401562
    legacy_id: v004
  I1KG81133:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG81133
      total_pages: 644
      volume_number: 21
      volume_pages_bdrc_intro: 2
    order: 21
    base_file: I1KG81133.txt
    statistics:
      ocr_word_median_confidence_index: 0.99
      ocr_word_mean_confidence_index: 0.9660760649875622
    legacy_id: v021
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
